### ISSUE TITLE
Make develop the default branch

### ISSUE THREAD

**Issue by szepeviktor** [decodelabs/fluidity#3]
...as contributors should send PR-s to the develop branch.

**Comment by betterthanclay** [comment]
I've gone back and forth on this issue - most advice ultimately ends up sticking with master / main as your default branch as it should be the responsibility of developers to direct pull requests to the correct branch. The default branch should be the one that gives the end user a stable environment.

In practise, that then leaves pull requests prone to targeting the wrong branch. There isn't really a good solution.
I've set it to develop for now, but may switch back again.

There's a good discussion about it here - https://github.com/OriginProtocol/origin-js/issues/123

**Comment by szepeviktor** [comment]
I have an idea...
